### PR TITLE
Create a docker file

### PR DESCRIPTION
**Pull request by nataliiazab**
Farnoosh and I completed ticket #6. @momahboobian and @LorenaCapraru please review as soon as you can.

- [x] A docker file of Good PR that runs the container on a laptop has been created

Step-by-step instruction to check if its working:
- **Download Docker Desktop** to your machine - [link](https://www.docker.com/products/docker-desktop/)

- Open '[Natalie-ticket-6-create-docker-file](https://github.com/nataliiazab/good-pr/tree/Natalie-ticket-6-create-docker-file)' branch on your machine

- **Build the docker image locally**:  `docker build --progress plain -t good-pr-docker:latest .`

- Optional:  Write the "`docker images`" command that lists all the Docker images that are currently stored on your local machine. 

The result should be similar to this one:
> REPOSITORY       TAG       IMAGE ID       CREATED          SIZE  
> good-pr-docker   latest    4a69f1526d48   2 minutes ago   184MB

- **Run your container**:  `docker run -p 3000:3000 good-pr-docker       `

### CODE REVIEW

**Comment by textbook** [comment]
Given the command that's being run (`npm run dev`) and the mounting of the source directory into the container (not to mention a suspiciously large image size), this looks like a _development_ setup. It's certainly nothing like the official examples I shared in Slack, which are production images. I thought the point of the story was to set up Docker for _production_?

**Comment by nataliiazab** [comment]
> Given the command that's being run (`npm run dev`) and the mounting of the source directory into the container (not to mention a suspiciously large image size), this looks like a _development_ setup. It's certainly nothing like the official examples I shared in Slack, which are production images. I thought the point of the story was to set up Docker for _production_?

this is a very valid comment, thank you @textbook. I've changed the Dockerfile to the one mentioned in the official documentation and added the .dockerignore file - the image size is 184MB now.  Please see if it's okay now

**Comment by textbook** [comment]
That seems a lot more reasonable, about 10% the previous size! It's a more production-ready setup. I'd suggest you all read through that Dockerfile and think about what it's doing, as there is at least one part that's definitely not needed for this particular app.

**Comment by nataliiazab** [comment]
> That seems a lot more reasonable, about 10% the previous size! It's a more production-ready setup. I'd suggest you all read through that Dockerfile and think about what it's doing, as there is at least one part that's definitely not needed for this particular app.

I've been able to detect only the lines for the package manager we don't use. (committed the change to delete them). In case you have some time for this - let us know if there is anything else we can safely delete. 

 thanks again for guiding me in the right direction with the production set-up!

**Review by momahboobian — APPROVED** [review]
@nataliiazab and @Farnooshmo,
Great job you did, well done. 👌🏻
and Also thanks Jon @textbook :) 
Docker file is ready for production.

**Pull request merged**
